trigger:
- main

pool:
  name: default

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'C:\agent\_work\1\s\Javateam\pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
